<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="14382" started-at="2023-04-27T15:57:17 EDT" finished-at="2023-04-27T15:57:31 EDT">
    <groups>
    </groups>
    <test name="Default test" duration-ms="14382" started-at="2023-04-27T15:57:17 EDT" finished-at="2023-04-27T15:57:31 EDT">
      <class name="variousConcepts_TestNG.HWS4_TestNG">
        <test-method status="PASS" signature="readConfig()[pri:0, instance:variousConcepts_TestNG.HWS4_TestNG@1500955a]" name="readConfig" is-config="true" duration-ms="8" started-at="2023-04-27T15:57:17 EDT" finished-at="2023-04-27T15:57:17 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readConfig -->
        <test-method status="PASS" signature="init()[pri:0, instance:variousConcepts_TestNG.HWS4_TestNG@1500955a]" name="init" is-config="true" duration-ms="3296" started-at="2023-04-27T15:57:17 EDT" finished-at="2023-04-27T15:57:20 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="LogInTest()[pri:1, instance:variousConcepts_TestNG.HWS4_TestNG@1500955a]" name="LogInTest" duration-ms="1319" started-at="2023-04-27T15:57:20 EDT" finished-at="2023-04-27T15:57:22 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogInTest -->
        <test-method status="PASS" signature="TearDown()[pri:0, instance:variousConcepts_TestNG.HWS4_TestNG@1500955a]" name="TearDown" is-config="true" duration-ms="878" started-at="2023-04-27T15:57:22 EDT" finished-at="2023-04-27T15:57:23 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method status="PASS" signature="init()[pri:0, instance:variousConcepts_TestNG.HWS4_TestNG@1500955a]" name="init" is-config="true" duration-ms="2407" started-at="2023-04-27T15:57:23 EDT" finished-at="2023-04-27T15:57:25 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="FAIL" signature="AddCustomer()[pri:2, instance:variousConcepts_TestNG.HWS4_TestNG@1500955a]" name="AddCustomer" duration-ms="5600" started-at="2023-04-27T15:57:25 EDT" finished-at="2023-04-27T15:57:31 EDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Contact number not displayed expected [] but found [5683920223]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Contact number not displayed expected [] but found [5683920223]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at variousConcepts_TestNG.HWS4_TestNG.AddCustomer(HWS4_TestNG.java:177)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddCustomer -->
        <test-method status="PASS" signature="TearDown()[pri:0, instance:variousConcepts_TestNG.HWS4_TestNG@1500955a]" name="TearDown" is-config="true" duration-ms="833" started-at="2023-04-27T15:57:31 EDT" finished-at="2023-04-27T15:57:31 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- variousConcepts_TestNG.HWS4_TestNG -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
